name: mobx_aulanew
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  mobx_codegen: ^2.0.6
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


